game-관전포인트 데이터패칭
project-wins/react-wins pull request #103
Opened 2024-09-21 07:59 UTC by mya413

## #️⃣ 연관된 이슈

> #67 

## 📝 작업 내용

> - [x] 관전포인트 데이터패칭
> - [x] 관전포인트 데이터 패칭 로직 수정
> - [x] 관전포인트 관련 라우터 수정
> - [x] api 타임아웃 시간 수정

### 스크린샷 (선택)

## 💬 리뷰 요구사항(선택)

> ![8](https://github.com/user-attachments/assets/370862a9-4d66-42f7-bd14-a752396f02ea)
> 1) 관전포인트 api 데이터 요청 후 응답이 오기까지의 시간이 3.52s 가 걸립니다. 이 부분 어떻게 최적화를 하는 방법이 있을까요?
> 2) 페이지 처음 렌더링 시 오늘 날짜에 해당되는 데이터가 정상적으로 불러와지지만,
> 다른 날짜로 이동 후에는 오늘 날짜와 이전 날짜에 해당 되는 부분의 데이터에 schedule-next가 없어 이전 날짜가 마지막 요소로 불러와집니다.
> 이 부분에 대해서는 멘토님께 문의드릴 예정입니다.

2024-09-21 10:43 UTC, handje requested changes
1. api콜이 늦게 오는 상태는 초기는 스켈레톤을 이용하고 초기로딩 이후에는 tanstack-query로 캐싱하여 로딩을 줄이는 방법이 제일 적합할 것 같습니다.
2. 기존페이지도 똑같이 작동하는것 확인했습니다. 아마 최신경기가 오늘 경기라서 아직 업데이트가 안된 문제라고 생각이 듭니다 😄

2024-09-21 10:43 UTC, handje commented on src/api/api.ts
> +  timeout: 3600,
혹시 모를 지연을 방지하기 위해 timeout을 제거하는 것도 좋을 것 같습니다. 이부분은 선택적으로 해주세요

2024-09-21 10:43 UTC, handje commented on src/components/Game/WatchPoint/Pitcher/Table.tsx
>              <td>{gameScore?.visit}</td>
td부분이 홈과 원정 모두 속성이 같은값을 보여주는걸로 확인되는데, 이부분을 배열로 묶어서 돌리는 방법은 없을까요? 같은 태그가 너무 반복되는 것으로 보입니다!
예를 들어 const label=['visit','playerName'] ; label.map((item)=><td>{visitPitcher[item]}</td>과 같이 반복되는 부분을 줄일수 있을것같습니다.

2024-09-21 10:43 UTC, handje commented on src/components/Game/WatchPoint/Record/Header.tsx
>          <Button
버튼을 다른 컴포넌트에서도 사용하시나요? 양쪽에만 사용된다면, 공통 속성은 Button에 아예 넣어두고 다른 부분만 props로 받는것이 코드를 줄일수있을 것 같습니다 :)

2024-09-22 05:58 UTC, mya413 commented on src/components/Game/WatchPoint/Pitcher/Table.tsx
>              <td>{gameScore?.visit}</td>
아직 tanstack-table 로직을 적용하지 않아서, 테이블 로직으로 나중에 리팩토링 할 것을 생각해 하드코딩을 했었습니다!
반복되는 코드를 일단 줄여볼게요!

2024-09-22 08:42 UTC, mya413 commented on src/api/api.ts
> +  timeout: 3600,
![9](https://github.com/user-attachments/assets/4c9f7507-cc19-4b90-886a-dc91d95aca40)

캡쳐와 같이 timeout을 제거했더니, strictmode에서 요청이 2번 들어가게 되어 문제가 생겼습니다.
첫번째 요청이 fullfiled 되었을 때 정상적으로 작동하는 것 처럼 보이지만,
두번째 요청이 pending 상태에서 fullfiled가 되었을 경우 오늘 날짜의 데이터로 다시 렌더링되는 현상이 있습니다.
strictmode는 배포시에는 적용되지 않으니 timeout을 지우는게 상관 없을까요?

2024-09-22 09:04 UTC, mya413 commented on src/components/Game/WatchPoint/Record/Header.tsx
>          <Button
동준님과 로고, 버튼 부분이 동일해서 Game/Common/ControllButton 경로로 수정하였습니다.

2024-09-24 03:26 UTC, handje approved these changes
resolve처리 누르고 merge해주세요~!🚀

2024-09-24 05:36 UTC, sdj799 approved these changes

2024-09-24 07:29 UTC, merged