응원단페이지 API 연결
project-wins/react-wins pull request #107
Opened 2024-09-21 16:06 UTC by Jieuneenee

## #️⃣ 연관된 이슈

> ex) #이슈번호, #이슈번호

## 📝 작업 내용

응원단 페이지  API 연결했습니다!
<img width="831" alt="스크린샷 2024-09-22 오전 1 03 35" src="https://github.com/user-attachments/assets/8e2eb19e-94d1-4dea-a9b8-5614740710e1">

### 스크린샷 (선택)

## 💬 리뷰 요구사항(선택)
커밋메세지 잘못적었네요ㅠㅠ  죄송해요 ㅠㅠ

2024-09-23 00:03 UTC, mya413 requested changes

2024-09-23 00:03 UTC, mya413 commented on src/components/Cheer/CheerInfo.tsx
>          </InfoUl>
`<li></li>` 내부가 동일하게 반복되는 것으로 보이는데, 반복렌더링으로 리팩토링 해보는건 어떠신가요?
예를 들면, ProfileDD의 각 요소를 배열에 담아서 map으로 화면에 렌더링 해주면 유지보수가 더 용이할 것 같아요!

2024-09-23 00:03 UTC, mya413 commented on src/pages/Cheer.tsx
>    height: 620px;
height 높이는 컨텐츠에 따라 달라지는데, 픽셀로 고정하신 이유가 궁금합니다!

2024-09-23 00:04 UTC, mya413 requested changes
해당 작업내용 이슈 생성해주시고, 이슈 연결해주세요!!

2024-09-24 08:01 UTC, mya413 reviewed
배포 문제만 (손)지은님께 여쭤보고 merge 진행해주시면 될 것 같습니다!

2024-09-26 09:21 UTC, handje approved these changes

2024-09-26 09:46 UTC, merged