Feature/game/boxscore 마크업 및 레이아웃
project-wins/react-wins pull request #60
Opened 2024-09-16 13:17 UTC by sdj799

## #️⃣ 연관된 이슈

> 

## 📝 작업 내용

> game/boxscore 마크업 및 레이아웃, 라우터 지정

### 스크린샷 (선택)
![image](https://github.com/user-attachments/assets/66c6511c-e36c-473d-a87d-60563387200c)

## 💬 리뷰 요구사항(선택)

2024-09-17 01:33 UTC, mya413 requested changes
[boxscore 마크업 및 레이아웃] design 라벨로 이슈 하나 생성해주시고,
PR 내용에 연관된 이슈로 연결해주세요!

2024-09-17 01:33 UTC, mya413 commented on src/components/BoxScore/MainTable.tsx
> +  const [data, _setData] = useState(() => [...boxScore.data.etcgames]);
그냥 setData와 언더바(_)가 들어가는 setData의 차이가 있나요?
이전 PR에서도 동준님은 이렇게 set함수명을 이렇게 지정하시는 것 같아서 언더바가 들어가고 안들어가고의 차이가 궁금해서요!

2024-09-17 01:33 UTC, mya413 commented on src/pages/BoxScore.tsx
> +          <LocationTitle title="주요 기록" />
동준님이 디자인해주신 LocationTitle이 게임 페이지 여러곳에서 사용될 것 같은데,
`components/common` 경로에 Title이라는 명칭으로 리팩토링 해주실 수 있으실까요?

2024-09-17 04:42 UTC, sdj799 commented on src/pages/BoxScore.tsx
> +          <LocationTitle title="주요 기록" />
맞아요! 공통으로 사용해서 일단은 만들고 나중에 리펙토링 과정에서 합치려고 생각했습니다.

2024-09-17 04:43 UTC, sdj799 commented on src/components/BoxScore/MainTable.tsx
> +  const [data, _setData] = useState(() => [...boxScore.data.etcgames]);
저도 보통은 언더바를 사용하진 않는데 공식문서에서 지정되어있어서 일단은 수정하지 않고 사용하였습니다.

2024-09-17 08:34 UTC, handje commented on src/pages/BoxScore.tsx
> +          <LocationTitle title="주요 기록" />
이부분은 제가 common에 생성해두었습니다! 합치는건 추후에 할게요. 이미 개발하신분들은 그대로 하시고 나머지 분들은 common사용하시면 됩니다!

2024-09-18 06:35 UTC, mya413 approved these changes
LGTM🚀🚀

2024-09-18 06:45 UTC, merged